# Generated by Django 4.1.7 on 2023-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=45)),
                ('ingredients', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('date_creation', models.DateField()),
                ('auteur', models.CharField(max_length=20)),
            ],
        ),
    ]
